// Bangladesh Meal Database
// Complete collection of authentic Bangladesh dishes with nutrition data

export interface BangladeshMeal {
    id: string;
    name: string;           // Bangla name
    nameEn: string;        // English name
    category: 'breakfast' | 'lunch' | 'dinner' | 'snack';
    calories: number;
    protein: number;       // grams
    carbs: number;         // grams
    fat: number;           // grams
    ingredients: string[]; // Key ingredients
    description: string;   // Brief description
    prepTime: string;      // Preparation time
    servings: number;      // Standard servings
    isVegetarian: boolean;
    isVegan: boolean;
    tags: string[];        // e.g., 'traditional', 'popular', 'healthy'
}

// 🌅 BREAKFAST MEALS (Nashta)
export const breakfastMeals: BangladeshMeal[] = [
    {
        id: 'bf001',
        name: 'পরোটা ও ডিম',
        nameEn: 'Paratha with Egg',
        category: 'breakfast',
        calories: 400,
        protein: 18,
        carbs: 45,
        fat: 15,
        ingredients: ['Flour', 'Eggs', 'Oil', 'Onion', 'Green Chili'],
        description: 'Traditional flatbread with scrambled or fried eggs',
        prepTime: '20 minutes',
        servings: 1,
        isVegetarian: false,
        isVegan: false,
        tags: ['traditional', 'popular', 'protein-rich'],
    },
    {
        id: 'bf002',
        name: 'খিচুড়ি',
        nameEn: 'Khichuri',
        category: 'breakfast',
        calories: 380,
        protein: 12,
        carbs: 60,
        fat: 8,
        ingredients: ['Rice', 'Lentils', 'Vegetables', 'Spices'],
        description: 'Rice and lentil porridge, comfort food',
        prepTime: '30 minutes',
        servings: 1,
        isVegetarian: true,
        isVegan: true,
        tags: ['traditional', 'healthy', 'comfort-food'],
    },
    {
        id: 'bf003',
        name: 'রুটি ও সবজি',
        nameEn: 'Roti with Sabji',
        category: 'breakfast',
        calories: 320,
        protein: 10,
        carbs: 52,
        fat: 6,
        ingredients: ['Wheat Flour', 'Mixed Vegetables', 'Spices'],
        description: 'Whole wheat bread with vegetable curry',
        prepTime: '25 minutes',
        servings: 1,
        isVegetarian: true,
        isVegan: true,
        tags: ['healthy', 'vegetarian', 'light'],
    },
    {
        id: 'bf004',
        name: 'পুরি ও আলু ভাজি',
        nameEn: 'Puri with Aloo Bhaji',
        category: 'breakfast',
        calories: 450,
        protein: 8,
        carbs: 58,
        fat: 20,
        ingredients: ['Flour', 'Potatoes', 'Oil', 'Spices'],
        description: 'Deep-fried bread with spiced potato curry',
        prepTime: '30 minutes',
        servings: 1,
        isVegetarian: true,
        isVegan: true,
        tags: ['traditional', 'festive', 'indulgent'],
    },
    {
        id: 'bf005',
        name: 'ব্রেড ও অমলেট',
        nameEn: 'Bread with Omelette',
        category: 'breakfast',
        calories: 350,
        protein: 20,
        carbs: 35,
        fat: 12,
        ingredients: ['Bread', 'Eggs', 'Onion', 'Tomato', 'Green Chili'],
        description: 'Toast with egg omelette',
        prepTime: '15 minutes',
        servings: 1,
        isVegetarian: false,
        isVegan: false,
        tags: ['quick', 'protein-rich', 'modern'],
    },
    {
        id: 'bf006',
        name: 'ডাল পুরি',
        nameEn: 'Daal Puri',
        category: 'breakfast',
        calories: 420,
        protein: 14,
        carbs: 55,
        fat: 16,
        ingredients: ['Flour', 'Lentils', 'Onion', 'Spices'],
        description: 'Puri stuffed with spiced lentils',
        prepTime: '35 minutes',
        servings: 1,
        isVegetarian: true,
        isVegan: true,
        tags: ['traditional', 'popular', 'filling'],
    },
    {
        id: 'bf007',
        name: 'লুচি ও আলুর দম',
        nameEn: 'Luchi with Alur Dom',
        category: 'breakfast',
        calories: 480,
        protein: 10,
        carbs: 62,
        fat: 22,
        ingredients: ['Refined Flour', 'Potatoes', 'Tomato', 'Spices'],
        description: 'Puffed fried bread with spicy potato curry',
        prepTime: '40 minutes',
        servings: 1,
        isVegetarian: true,
        isVegan: true,
        tags: ['festive', 'traditional', 'indulgent'],
    },
    {
        id: 'bf008',
        name: 'সিঙ্গারা',
        nameEn: 'Singara (2 pieces)',
        category: 'breakfast',
        calories: 300,
        protein: 6,
        carbs: 40,
        fat: 14,
        ingredients: ['Flour', 'Potatoes', 'Peas', 'Spices'],
        description: 'Fried triangular pastry with potato filling',
        prepTime: '10 minutes',
        servings: 1,
        isVegetarian: true,
        isVegan: true,
        tags: ['street-food', 'snack', 'popular'],
    },
    {
        id: 'bf009',
        name: 'পিঠা',
        nameEn: 'Pitha (Chitoi/Bhapa)',
        category: 'breakfast',
        calories: 250,
        protein: 4,
        carbs: 48,
        fat: 4,
        ingredients: ['Rice Flour', 'Coconut', 'Jaggery'],
        description: 'Traditional rice cake, various types',
        prepTime: '30 minutes',
        servings: 1,
        isVegetarian: true,
        isVegan: false,
        tags: ['traditional', 'winter-special', 'sweet'],
    },
    {
        id: 'bf010',
        name: 'মুড়ি ও চানাচুর',
        nameEn: 'Muri with Chanachur',
        category: 'breakfast',
        calories: 200,
        protein: 5,
        carbs: 35,
        fat: 4,
        ingredients: ['Puffed Rice', 'Peanuts', 'Mustard Oil', 'Spices'],
        description: 'Puffed rice with spicy mix',
        prepTime: '5 minutes',
        servings: 1,
        isVegetarian: true,
        isVegan: true,
        tags: ['quick', 'light', 'popular'],
    },
];

// 🍛 LUNCH MEALS (Dupur er Khabar)
export const lunchMeals: BangladeshMeal[] = [
    {
        id: 'ln001',
        name: 'ভাত, ডাল, মাছ ও সবজি',
        nameEn: 'Bhaat, Daal, Machh, Sabji',
        category: 'lunch',
        calories: 650,
        protein: 35,
        carbs: 85,
        fat: 15,
        ingredients: ['Rice', 'Lentils', 'Fish', 'Mixed Vegetables'],
        description: 'Complete traditional meal with rice, lentils, fish curry, and vegetables',
        prepTime: '60 minutes',
        servings: 1,
        isVegetarian: false,
        isVegan: false,
        tags: ['traditional', 'complete-meal', 'balanced'],
    },
    {
        id: 'ln002',
        name: 'ভাত, মুরগির তরকারি ও সবজি',
        nameEn: 'Bhaat, Chicken Curry, Sabji',
        category: 'lunch',
        calories: 700,
        protein: 40,
        carbs: 80,
        fat: 18,
        ingredients: ['Rice', 'Chicken', 'Onion', 'Tomato', 'Vegetables'],
        description: 'Rice with chicken curry and vegetable side',
        prepTime: '60 minutes',
        servings: 1,
        isVegetarian: false,
        isVegan: false,
        tags: ['popular', 'protein-rich', 'filling'],
    },
    {
        id: 'ln003',
        name: 'পোলাও ও গরুর মাংস',
        nameEn: 'Polao with Beef Curry',
        category: 'lunch',
        calories: 800,
        protein: 45,
        carbs: 90,
        fat: 25,
        ingredients: ['Basmati Rice', 'Beef', 'Ghee', 'Spices'],
        description: 'Fragrant rice with spicy beef curry',
        prepTime: '90 minutes',
        servings: 1,
        isVegetarian: false,
        isVegan: false,
        tags: ['festive', 'rich', 'special-occasion'],
    },
    {
        id: 'ln004',
        name: 'বিরিয়ানি',
        nameEn: 'Biryani (Chicken/Mutton)',
        category: 'lunch',
        calories: 750,
        protein: 38,
        carbs: 85,
        fat: 22,
        ingredients: ['Basmati Rice', 'Chicken/Mutton', 'Yogurt', 'Spices'],
        description: 'Layered rice with spiced meat',
        prepTime: '120 minutes',
        servings: 1,
        isVegetarian: false,
        isVegan: false,
        tags: ['festive', 'popular', 'special'],
    },
    {
        id: 'ln005',
        name: 'ভাত, ভর্তা ও ডাল',
        nameEn: 'Bhaat, Bhorta, Daal',
        category: 'lunch',
        calories: 550,
        protein: 20,
        carbs: 80,
        fat: 12,
        ingredients: ['Rice', 'Mashed Vegetables', 'Lentils', 'Mustard Oil'],
        description: 'Rice with mashed vegetables and lentils',
        prepTime: '45 minutes',
        servings: 1,
        isVegetarian: true,
        isVegan: true,
        tags: ['traditional', 'healthy', 'simple'],
    },
    {
        id: 'ln006',
        name: 'ভাত, ডিমের তরকারি ও সবজি',
        nameEn: 'Bhaat, Egg Curry, Sabji',
        category: 'lunch',
        calories: 580,
        protein: 25,
        carbs: 75,
        fat: 14,
        ingredients: ['Rice', 'Eggs', 'Tomato', 'Onion', 'Vegetables'],
        description: 'Rice with egg curry and vegetable side',
        prepTime: '45 minutes',
        servings: 1,
        isVegetarian: false,
        isVegan: false,
        tags: ['economical', 'protein-rich', 'everyday'],
    },
    {
        id: 'ln007',
        name: 'তেহারি',
        nameEn: 'Tehari',
        category: 'lunch',
        calories: 680,
        protein: 30,
        carbs: 82,
        fat: 18,
        ingredients: ['Rice', 'Beef/Chicken', 'Potatoes', 'Spices'],
        description: 'Yellow rice with meat and potatoes',
        prepTime: '75 minutes',
        servings: 1,
        isVegetarian: false,
        isVegan: false,
        tags: ['traditional', 'popular', 'aromatic'],
    },
    {
        id: 'ln008',
        name: 'খিচুড়ি ও গরুর মাংস',
        nameEn: 'Khichuri with Beef',
        category: 'lunch',
        calories: 720,
        protein: 35,
        carbs: 78,
        fat: 20,
        ingredients: ['Rice', 'Lentils', 'Beef', 'Vegetables', 'Spices'],
        description: 'Rice-lentil mix with beef curry',
        prepTime: '60 minutes',
        servings: 1,
        isVegetarian: false,
        isVegan: false,
        tags: ['comfort-food', 'filling', 'traditional'],
    },
    {
        id: 'ln009',
        name: 'ভাত, শাক ও মাছ',
        nameEn: 'Bhaat, Shak, Machh',
        category: 'lunch',
        calories: 600,
        protein: 32,
        carbs: 75,
        fat: 12,
        ingredients: ['Rice', 'Leafy Greens', 'Fish', 'Garlic'],
        description: 'Rice with greens and fish',
        prepTime: '50 minutes',
        servings: 1,
        isVegetarian: false,
        isVegan: false,
        tags: ['healthy', 'traditional', 'nutritious'],
    },
    {
        id: 'ln010',
        name: 'মিক্সড ভেজিটেবল রাইস',
        nameEn: 'Mixed Vegetable Rice',
        category: 'lunch',
        calories: 620,
        protein: 22,
        carbs: 88,
        fat: 15,
        ingredients: ['Rice', 'Mixed Vegetables', 'Paneer/Tofu', 'Spices'],
        description: 'Rice with assorted vegetables',
        prepTime: '50 minutes',
        servings: 1,
        isVegetarian: true,
        isVegan: false,
        tags: ['healthy', 'colorful', 'balanced'],
    },
];

// 🌙 DINNER MEALS (Rater Khabar)
export const dinnerMeals: BangladeshMeal[] = [
    {
        id: 'dn001',
        name: 'রুটি ও মুরগি',
        nameEn: 'Roti with Chicken',
        category: 'dinner',
        calories: 550,
        protein: 35,
        carbs: 55,
        fat: 15,
        ingredients: ['Wheat Flour', 'Chicken', 'Onion', 'Tomato'],
        description: 'Flatbread with chicken curry',
        prepTime: '45 minutes',
        servings: 1,
        isVegetarian: false,
        isVegan: false,
        tags: ['popular', 'lighter', 'protein-rich'],
    },
    {
        id: 'dn002',
        name: 'খিচুড়ি (হালকা)',
        nameEn: 'Khichuri (Light)',
        category: 'dinner',
        calories: 420,
        protein: 15,
        carbs: 65,
        fat: 8,
        ingredients: ['Rice', 'Lentils', 'Light Spices'],
        description: 'Light rice and lentil porridge',
        prepTime: '30 minutes',
        servings: 1,
        isVegetarian: true,
        isVegan: true,
        tags: ['light', 'easy-digest', 'comfort-food'],
    },
    {
        id: 'dn003',
        name: 'ফ্রাইড রাইস',
        nameEn: 'Fried Rice',
        category: 'dinner',
        calories: 580,
        protein: 20,
        carbs: 75,
        fat: 18,
        ingredients: ['Rice', 'Vegetables', 'Eggs', 'Soy Sauce'],
        description: 'Stir-fried rice with vegetables and eggs',
        prepTime: '25 minutes',
        servings: 1,
        isVegetarian: false,
        isVegan: false,
        tags: ['quick', 'popular', 'tasty'],
    },
    {
        id: 'dn004',
        name: 'ভাত ও হালকা তরকারি',
        nameEn: 'Bhaat with Light Curry',
        category: 'dinner',
        calories: 500,
        protein: 25,
        carbs: 70,
        fat: 10,
        ingredients: ['Rice', 'Light Curry', 'Vegetables'],
        description: 'Rice with light vegetable curry',
        prepTime: '35 minutes',
        servings: 1,
        isVegetarian: true,
        isVegan: true,
        tags: ['light', 'healthy', 'easy-digest'],
    },
    {
        id: 'dn005',
        name: 'পরোটা ও ভাজি',
        nameEn: 'Paratha with Bhaji',
        category: 'dinner',
        calories: 480,
        protein: 12,
        carbs: 60,
        fat: 18,
        ingredients: ['Flour', 'Mixed Vegetables', 'Spices'],
        description: 'Layered flatbread with vegetable curry',
        prepTime: '30 minutes',
        servings: 1,
        isVegetarian: true,
        isVegan: true,
        tags: ['traditional', 'satisfying', 'vegetarian'],
    },
    {
        id: 'dn006',
        name: 'নুডুলস (বাংলাদেশি স্টাইল)',
        nameEn: 'Noodles (Bangladeshi Style)',
        category: 'dinner',
        calories: 520,
        protein: 18,
        carbs: 68,
        fat: 16,
        ingredients: ['Noodles', 'Vegetables', 'Eggs', 'Spices'],
        description: 'Stir-fried noodles with local spices',
        prepTime: '20 minutes',
        servings: 1,
        isVegetarian: false,
        isVegan: false,
        tags: ['quick', 'modern', 'popular'],
    },
    {
        id: 'dn007',
        name: 'রুটি ও ডাল',
        nameEn: 'Roti with Daal',
        category: 'dinner',
        calories: 400,
        protein: 16,
        carbs: 58,
        fat: 8,
        ingredients: ['Wheat Flour', 'Lentils', 'Garlic', 'Cumin'],
        description: 'Flatbread with lentil curry',
        prepTime: '35 minutes',
        servings: 1,
        isVegetarian: true,
        isVegan: true,
        tags: ['light', 'healthy', 'protein-rich'],
    },
    {
        id: 'dn008',
        name: 'ভাত ও সবজির তরকারি',
        nameEn: 'Rice with Vegetable Curry',
        category: 'dinner',
        calories: 480,
        protein: 14,
        carbs: 72,
        fat: 12,
        ingredients: ['Rice', 'Mixed Vegetables', 'Coconut', 'Spices'],
        description: 'Rice with mixed vegetable curry',
        prepTime: '40 minutes',
        servings: 1,
        isVegetarian: true,
        isVegan: true,
        tags: ['healthy', 'colorful', 'light'],
    },
    {
        id: 'dn009',
        name: 'স্যুপ ও রুটি',
        nameEn: 'Soup with Roti',
        category: 'dinner',
        calories: 380,
        protein: 15,
        carbs: 50,
        fat: 10,
        ingredients: ['Vegetables', 'Wheat Flour', 'Chicken/Vegetable Broth'],
        description: 'Hot soup with flatbread',
        prepTime: '35 minutes',
        servings: 1,
        isVegetarian: true,
        isVegan: false,
        tags: ['light', 'healthy', 'comforting'],
    },
    {
        id: 'dn010',
        name: 'হালিম',
        nameEn: 'Haleem',
        category: 'dinner',
        calories: 600,
        protein: 32,
        carbs: 58,
        fat: 20,
        ingredients: ['Wheat', 'Lentils', 'Meat', 'Spices'],
        description: 'Thick meat and lentil stew',
        prepTime: '120 minutes',
        servings: 1,
        isVegetarian: false,
        isVegan: false,
        tags: ['special', 'festive', 'rich'],
    },
];

// 🍪 SNACK MEALS (Jhal Muri/Tea Time)
export const snackMeals: BangladeshMeal[] = [
    {
        id: 'sn001',
        name: 'ঝাল মুড়ি',
        nameEn: 'Jhal Muri',
        category: 'snack',
        calories: 150,
        protein: 4,
        carbs: 28,
        fat: 3,
        ingredients: ['Puffed Rice', 'Mustard Oil', 'Peanuts', 'Onion', 'Green Chili'],
        description: 'Spicy puffed rice mix, Bangladesh\'s favorite street snack',
        prepTime: '5 minutes',
        servings: 1,
        isVegetarian: true,
        isVegan: true,
        tags: ['street-food', 'light', 'popular'],
    },
    {
        id: 'sn002',
        name: 'সমুসা',
        nameEn: 'Samosa (2 pieces)',
        category: 'snack',
        calories: 280,
        protein: 6,
        carbs: 35,
        fat: 14,
        ingredients: ['Flour', 'Potatoes', 'Peas', 'Spices'],
        description: 'Fried pastry with savory filling',
        prepTime: '10 minutes',
        servings: 1,
        isVegetarian: true,
        isVegan: true,
        tags: ['popular', 'fried', 'street-food'],
    },
    {
        id: 'sn003',
        name: 'চটপটি',
        nameEn: 'Chotpoti',
        category: 'snack',
        calories: 200,
        protein: 8,
        carbs: 32,
        fat: 4,
        ingredients: ['Chickpeas', 'Potatoes', 'Tamarind', 'Spices'],
        description: 'Spicy chickpea and potato mix',
        prepTime: '10 minutes',
        servings: 1,
        isVegetarian: true,
        isVegan: true,
        tags: ['street-food', 'spicy', 'tangy'],
    },
    {
        id: 'sn004',
        name: 'ফুচকা',
        nameEn: 'Phuchka (6 pieces)',
        category: 'snack',
        calories: 180,
        protein: 5,
        carbs: 30,
        fat: 4,
        ingredients: ['Semolina', 'Potatoes', 'Chickpeas', 'Tamarind Water'],
        description: 'Crispy shells with tangy water',
        prepTime: '10 minutes',
        servings: 1,
        isVegetarian: true,
        isVegan: true,
        tags: ['street-food', 'tangy', 'popular'],
    },
    {
        id: 'sn005',
        name: 'বেগুনি',
        nameEn: 'Beguni',
        category: 'snack',
        calories: 220,
        protein: 4,
        carbs: 28,
        fat: 10,
        ingredients: ['Eggplant', 'Gram Flour', 'Spices'],
        description: 'Fried eggplant fritters',
        prepTime: '15 minutes',
        servings: 1,
        isVegetarian: true,
        isVegan: true,
        tags: ['street-food', 'fried', 'rainy-day'],
    },
    {
        id: 'sn006',
        name: 'কলা',
        nameEn: 'Banana',
        category: 'snack',
        calories: 100,
        protein: 1,
        carbs: 25,
        fat: 0,
        ingredients: ['Banana'],
        description: 'Fresh banana, healthy snack',
        prepTime: '1 minute',
        servings: 1,
        isVegetarian: true,
        isVegan: true,
        tags: ['healthy', 'quick', 'natural'],
    },
    {
        id: 'sn007',
        name: 'মিক্সড ফ্রুটস',
        nameEn: 'Mixed Fruits',
        category: 'snack',
        calories: 120,
        protein: 2,
        carbs: 28,
        fat: 1,
        ingredients: ['Apple', 'Banana', 'Orange', 'Grapes'],
        description: 'Assorted fresh fruits',
        prepTime: '5 minutes',
        servings: 1,
        isVegetarian: true,
        isVegan: true,
        tags: ['healthy', 'fresh', 'vitamin-rich'],
    },
    {
        id: 'sn008',
        name: 'বিস্কুট ও চা',
        nameEn: 'Biscuits with Tea',
        category: 'snack',
        calories: 150,
        protein: 3,
        carbs: 25,
        fat: 5,
        ingredients: ['Biscuits', 'Tea', 'Sugar', 'Milk'],
        description: 'Tea with biscuits, classic afternoon snack',
        prepTime: '5 minutes',
        servings: 1,
        isVegetarian: true,
        isVegan: false,
        tags: ['quick', 'tea-time', 'everyday'],
    },
    {
        id: 'sn009',
        name: 'সেদ্ধ ডিম',
        nameEn: 'Boiled Eggs (2)',
        category: 'snack',
        calories: 140,
        protein: 12,
        carbs: 2,
        fat: 10,
        ingredients: ['Eggs'],
        description: 'Two boiled eggs, protein-rich snack',
        prepTime: '10 minutes',
        servings: 1,
        isVegetarian: false,
        isVegan: false,
        tags: ['healthy', 'protein-rich', 'simple'],
    },
    {
        id: 'sn010',
        name: 'ভাজা বাদাম',
        nameEn: 'Roasted Peanuts',
        category: 'snack',
        calories: 160,
        protein: 7,
        carbs: 15,
        fat: 8,
        ingredients: ['Peanuts', 'Salt'],
        description: 'Roasted peanuts with salt',
        prepTime: '2 minutes',
        servings: 1,
        isVegetarian: true,
        isVegan: true,
        tags: ['crunchy', 'protein-rich', 'portable'],
    },
];

// Complete meal database
export const allBangladeshMeals: BangladeshMeal[] = [
    ...breakfastMeals,
    ...lunchMeals,
    ...dinnerMeals,
    ...snackMeals,
];

// Helper functions
export const getMealsByCategory = (category: 'breakfast' | 'lunch' | 'dinner' | 'snack'): BangladeshMeal[] => {
    return allBangladeshMeals.filter(meal => meal.category === category);
};

export const getVegetarianMeals = (): BangladeshMeal[] => {
    return allBangladeshMeals.filter(meal => meal.isVegetarian);
};

export const getMealById = (id: string): BangladeshMeal | undefined => {
    return allBangladeshMeals.find(meal => meal.id === id);
};

export const getMealsByTag = (tag: string): BangladeshMeal[] => {
    return allBangladeshMeals.filter(meal => meal.tags.includes(tag));
};
